### ISSUE TITLE
I think that's something wrong with the docker image...

### ISSUE THREAD

**Issue by esturniolo** [oppiliappan/lurker#4]
Just this. Please take a look to the image:

![imagen](https://github.com/user-attachments/assets/ae387b98-cecb-4689-a6d0-276c4aabf73c)

**Comment by ma-04** [comment]
can confirm, I can see the same thing. Probably a pipeline issue.

**Comment by oppiliappan** [comment]
this is a reproducability guarantee of the nix build system. time is pinned to epoch time in all builds. see https://nixos.org/manual/nixpkgs/stable/#ssec-pkgs-dockerTools-buildImage-inputs: 

```
created (String; optional)
Specifies the time of creation of the generated image. This should be either a date and time formatted according to [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) or "now", in which case buildImage will use the current date.

See [Example 306](https://nixos.org/manual/nixpkgs/stable/#ex-dockerTools-buildImage-creatednow) for how to use "now".

Caution
Using "now" means that the generated image will not be reproducible anymore (because the date will always change whenever it’s built).

Default value: "1970-01-01T00:00:01Z".
```

is there an issue with the the creation time being pinned to epoch time?

**Comment by ma-04** [comment]
@oppiliappan  Thanks for pointing it out.
> is there an issue with the the creation time being pinned to epoch time?

Nothing major. And as far as I understand, docker can handle image update as long as there's a change of the image hash. 
Though it might cause some confusion if someone looks at it without knowing about this, like I did.

**Comment by oppiliappan** [comment]
> Nothing major. And as far as I understand, docker can handle image update as long as there's a change of the image hash.
> Though it might cause some confusion if someone looks at it without knowing about this, like I did.

i will put instructions in the readme regarding docker images, with a note about the timestamp problem. i would like to keep this behaviour because using `created = "now"` breaks the reproducable builds guarantee.
