### ISSUE TITLE
Docker container not saving accounts or subscriptions

### ISSUE THREAD

**Issue by chucklefart** [oppiliappan/lurker#5]
Every time I  restart the docker container I have to make a new account, etc.
I assume this is because the lurker.db needs to be mounted to the container somewhere, but I can't work out where it should go.

As as aside, this is amazing and everything I've wanted since the reddit API changes, so thank you :)

**Comment by guitarer09** [comment]
You need to create a volume for the container to permanently save data to.

Here's my docker-compose:

`lurker:
    image: ghcr.io/oppiliappan/lurker:latest
    container_name: lurker
    network_mode: service:ts-lurker
    restart: unless-stopped
    volumes:
      - ./lurker:/data`

**Comment by oppiliappan** [comment]
to add on to @guitarer09 's reply, you can also invoke docker at the command line with the `-v` flag like so:

```
docker run -v /host/path:/data lurker:latest
```

i will add this to the readme of the repository.
