### ISSUE TITLE
Feature Request: Post Search

### ISSUE THREAD

**Issue by guitarer09** [oppiliappan/lurker#6]
Just got Lurker up and running for myself and a few friends. Loving it so far! I think the only thing I'm missing is the ability to search for posts (header/body). I use Reddit quite a bit for info gathering as much as I do entertainment.

**Comment by oppiliappan** [comment]
i am still working out a good ux for this, for now, the search page includes two search bars: one for subreddits and one for posts (soon, one for users).
![search_bars](https://github.com/user-attachments/assets/87d1d57a-bcdb-4ba7-9935-1c45c208538d)

**Comment by oppiliappan** [comment]
latest docker image contains the post-search feature!
