### ISSUE TITLE
SSO/Header Authorization

### ISSUE THREAD

**Issue by voc0der** [oppiliappan/lurker#8]
I looked at the code, and I'm installing this now behind an authelia IdP. It doesn't look like the user system will accept a `REMOTE_USER` or similar authorization header.

Definitely way too soon to be talking about OIDC.  If you added an env that a user explicitly set a remote http header, e.g. `REMOTE_USER` or similar maybe we could have people bypass any authentication?

https://github.com/wheelybird/ldap-user-manager/blob/ce92321285129d34d44ba1babe72b4d09e893a44/www/includes/web_functions.inc.php#L95

**Comment by voc0der** [comment]
https://github.com/voc0der/lurker

I can make a PR if you want.

Since my environment has authelia around it, it's not trivial to test the old user/pass method for me, otherwise I'd of just made a PR.

tag is `voc0der/lurker:latest`.

**Comment by oppiliappan** [comment]
if i understand correctly, does this add the ability to skip the authentication page? i am afraid i dont really know what authelia/IdP/OIDC are. that being said, ill take a look at the submitted PR, thanks!
